theme: jekyll-theme-minimal
title: Ikram Ali
description: A collection of technical blogs and talks on machine learning and data science.
show_downloads: false
google_analytics: UA-44088367-1
logo: ./ikram.JPG